pub mod ifnode_test;
pub mod print_node_test;
pub mod number_node_test;
pub mod sequence_node_test;
pub mod let_node_test;
pub mod var_node_test;
pub mod string_node_test;
pub mod expression_node_test;
pub mod goto_node_test;
